---
name: "CI"
on:
  push:
  pull_request:
    types: [opened, reopened, edited]
  workflow_call:
jobs:
  lint:
    name: "Run linter"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.6
      - name: Check Formatting & Linting
        run: nix develop --command just check
  cc:
    name: "Conventional Commits"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check commit messages
        shell: bash
        run: |-
          readarray -t messages < <(git log --format=%s)

          fails=()
          for message in "${messages[@]}"; do
              echo "$message" | grep -Eq '^(build|chore|ci|docs|feat|fix|refactor|revert|style|test)(\([a-zA-Z0-9_-]+\))?!?: .+( #[0-9]+)?$' || {
                  echo "The commit message '$message' does not conform to the configured regex!";
                  fails+=($message);
              }
          done

          echo "## Build Results  " >> $GITHUB_STEP_SUMMARY
          if (( ${#fails[@]} == 0 )); then
              echo "All commits are a-okay." >> $GITHUB_STEP_SUMMARY
              exit 0
          fi

          echo "The following commit messages do not conform:  " >> $GITHUB_STEP_SUMMARY
          for fail in "${fails[@]}"; do
            echo "- $fail  " >> $GITHUB_STEP_SUMMARY
          done

          exit 1
  build:
    name: Build
    needs:
      - cc
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build
        run: nix develop --command just build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/_site/
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
